### ISSUE TITLE
We don't think you're doing a right thing!

### ISSUE THREAD

**Issue by cloudtuotuo** [syno-community/rr#4]
This shouldn't be published, you know that.

**Comment by syno-community** [comment]
Are you the author or the author's representative?
Please talk about what is right and what is not right when you use this to bypass and use DSM. So you still talk about being right?
If the author publishes on this channel (github), this repository will not be available. The author understands very clearly that wherever it is published, it is inevitable that there will be a number of other sharing channels. Unless he stops releasing it publicly.
